[build]
  command = "npm run build-static"
  publish = "out"

# Configuration pour Next.js
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  # Optimisation pour Next.js (pas de NODE_ENV non-standard)
  NETLIFY_USE_FFMPEG = "true"
  NEXT_PUBLIC_NETLIFY_DEPLOYMENT = "true"
  # Chemins pour FFmpeg et FFprobe
  FFMPEG_PATH = "/usr/bin/ffmpeg"
  FFPROBE_PATH = "/usr/bin/ffprobe"
  NODE_OPTIONS = "--max_old_space_size=4096"
  # Augmentation du timeout de construction
  BUILD_TIMEOUT = "1800"
  NEXT_EXPORT = "true"

# Configuration des headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuration pour les fichiers statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Fallback pour SPA - toutes les routes non trouvées vont vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 